{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andatsoft.ext",
    "module": "resolver-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24676,
          "sha512": "fe4c455ad1e105ffb8f907ff6aaa177a669d1e08b75deb7c809811ac6a0f28c06cca6ab7ae994171ab7a0af849e3405835b5faa39240721727fc8182abc4ea12",
          "sha256": "e864a76606a2bc289f58537ee2e2c7b5cc2ede576f22db21690999fcb00aad5c",
          "sha1": "4154ad584f52f4d13a19b9777dc37663ed775d52",
          "md5": "0519c8e2482a8b7c708090f934c1730a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24676,
          "sha512": "fe4c455ad1e105ffb8f907ff6aaa177a669d1e08b75deb7c809811ac6a0f28c06cca6ab7ae994171ab7a0af849e3405835b5faa39240721727fc8182abc4ea12",
          "sha256": "e864a76606a2bc289f58537ee2e2c7b5cc2ede576f22db21690999fcb00aad5c",
          "sha1": "4154ad584f52f4d13a19b9777dc37663ed775d52",
          "md5": "0519c8e2482a8b7c708090f934c1730a"
        }
      ]
    }
  ]
}
