{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andatsoft.ext",
    "module": "resolver-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24426,
          "sha512": "9df7effd67c62ac851f28c51ce779a0cc31893247c0d548b37a1575c4388fb7060f90b98a1b9b9a10ed6ab220dd585c7b197b121f2100bcff23606e0f40c48df",
          "sha256": "6f0246f9b7c00c1b4656e0c3253569bd2c2a460cc13ad604c0fcc3d94a2b634d",
          "sha1": "cee895d0eb5d47b5a17f1dd755f2314d13052c1a",
          "md5": "42487cf5fdd3efc8c2ea61628bccca8c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24426,
          "sha512": "9df7effd67c62ac851f28c51ce779a0cc31893247c0d548b37a1575c4388fb7060f90b98a1b9b9a10ed6ab220dd585c7b197b121f2100bcff23606e0f40c48df",
          "sha256": "6f0246f9b7c00c1b4656e0c3253569bd2c2a460cc13ad604c0fcc3d94a2b634d",
          "sha1": "cee895d0eb5d47b5a17f1dd755f2314d13052c1a",
          "md5": "42487cf5fdd3efc8c2ea61628bccca8c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resolver-sdk-1.0.0-sources.jar",
          "url": "resolver-sdk-1.0.0-sources.jar",
          "size": 12935,
          "sha512": "0311978bb1681b0b041afa9803d7923fa78687477477cd1e0b731777eac4f4b6bad5778b624334162dab9195090d211988775c89029d6679d8b9a83f4354873d",
          "sha256": "581bae6421f51a0851100f709ce3a32366ec93ae10ef2da585c8f530fd00202a",
          "sha1": "ddc3ae02aed6cc7ee64d274f1d85490f5a180e92",
          "md5": "9c22a2ee30e2e0261f7f961039ebbaa6"
        }
      ]
    }
  ]
}
