{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andatsoft.ext",
    "module": "resolver-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24426,
          "sha512": "9df7effd67c62ac851f28c51ce779a0cc31893247c0d548b37a1575c4388fb7060f90b98a1b9b9a10ed6ab220dd585c7b197b121f2100bcff23606e0f40c48df",
          "sha256": "6f0246f9b7c00c1b4656e0c3253569bd2c2a460cc13ad604c0fcc3d94a2b634d",
          "sha1": "cee895d0eb5d47b5a17f1dd755f2314d13052c1a",
          "md5": "42487cf5fdd3efc8c2ea61628bccca8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "resolver-sdk-1.0.0.aar",
          "url": "resolver-sdk-1.0.0.aar",
          "size": 24426,
          "sha512": "9df7effd67c62ac851f28c51ce779a0cc31893247c0d548b37a1575c4388fb7060f90b98a1b9b9a10ed6ab220dd585c7b197b121f2100bcff23606e0f40c48df",
          "sha256": "6f0246f9b7c00c1b4656e0c3253569bd2c2a460cc13ad604c0fcc3d94a2b634d",
          "sha1": "cee895d0eb5d47b5a17f1dd755f2314d13052c1a",
          "md5": "42487cf5fdd3efc8c2ea61628bccca8c"
        }
      ]
    }
  ]
}
